MUSICIAN_PAGINATOR_COUNT = 10
SUBMIT_MUSICIAN_DATA_FILTER_RESET_URL = '/submit-musician-data'
COLLECTION_PAGINATOR_COUNT = 10
WORK_PAGINATOR_COUNT = 20
PERFORMANCE_PAGINATOR_COUNT = 30
INSTRUMENT_PAGINATOR_COUNT = 10
APPS_AND_NOTEBOOKS_PAGINATOR_COUNT = 5
APPS_AND_NOTEBOOKS_DATA_FILTER_RESET_URL = "/apps-and-notebooks"
