version: "3.0"

services:
  shiny:
    container_name: stelupa_api
    # To build the image locally, comment out "image" below, and uncomment
    # "build" and the lines indented under it.
    image: rocker/shiny
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    restart: always
    # Setting this to something other than 'root' will cause shiny apps not to
    # run on the localhost:80 "Welcome to Shiny" diagnostics page mentioned
    # below.
    user: 'root'
    ports:
      - '3838:3838'
      - '8000:8000'

    volumes:
      - './shinylog/:/var/log/shiny-server'
      - './shinyapps/:/srv/shiny-server'
      - './django/:/home'


volumes:
  shinylogs:
  shinyapps:
  django:
