# Generated by Django 2.2.4 on 2019-08-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('death_date', models.DateField()),
                ('birth_nationality', models.CharField(max_length=255)),
                ('death_nationality', models.CharField(max_length=255)),
                ('musician_type', models.CharField(max_length=255)),
                ('birth_location_latitude', models.FloatField()),
                ('birth_location_longitude', models.FloatField()),
                ('death_location_latitude', models.FloatField()),
                ('death_location_longitude', models.FloatField()),
                ('country_of_predominant_residency', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('period_type', models.CharField(max_length=255)),
                ('period_description', models.TextField()),
                ('location_based_in_latitude', models.FloatField(blank=True, null=True)),
                ('location_based_in_longitude', models.FloatField(blank=True, null=True)),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicians.Musician')),
            ],
        ),
    ]
