# Generated by Django 2.2.4 on 2019-08-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0003_auto_20190816_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='location',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
