# Generated by Django 2.2.4 on 2019-08-17 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicians', '0006_auto_20190817_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='period',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
