# Generated by Django 2.2.4 on 2019-08-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('musicians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('family', models.CharField(max_length=255)),
                ('patch', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('static_tempo', models.IntegerField()),
                ('date_composed', models.DateField(blank=True, null=True)),
                ('date_recorded', models.DateField(blank=True, null=True)),
                ('creation_location_latitude', models.FloatField()),
                ('creation_location_longitude', models.FloatField()),
                ('genre', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='musicians.Musician')),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('midi_number', models.IntegerField()),
                ('current_chord_root', models.CharField(max_length=255)),
                ('current_chord_root_as_int', models.CharField(max_length=255)),
                ('current_chord_type', models.CharField(max_length=255)),
                ('harmony_note_flag', models.BooleanField()),
                ('current_measure', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('duration_due_to_tied_notes', models.IntegerField()),
                ('location', models.IntegerField()),
                ('location_in_measure', models.IntegerField()),
                ('location_in_song_as_percentage', models.IntegerField()),
                ('time_signature_numerator', models.IntegerField()),
                ('time_signature_denominator', models.IntegerField()),
                ('quarter_beats_per_minute', models.IntegerField()),
                ('time_stamp', models.TimeField(auto_now_add=True)),
                ('voice', models.IntegerField()),
                ('work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.Work')),
            ],
        ),
    ]
