# Generated by Django 2.2.4 on 2019-08-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='notes',
            field=models.TextField(default='blah'),
            preserve_default=False,
        ),
    ]
