# Generated by Django 2.2.4 on 2019-08-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0004_work_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='date_composed',
            new_name='date_composed_end_date',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='date_recorded',
            new_name='date_composed_start_date',
        ),
        migrations.AddField(
            model_name='work',
            name='date_record_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='date_recorded_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
