# Generated by Django 2.2.4 on 2019-08-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20190806_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='is_grouping',
            field=models.BooleanField(default=False),
        ),
    ]
