# Generated by Django 2.2.4 on 2019-08-06 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0006_instrument_is_grouping'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='instrument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.Instrument'),
        ),
    ]
