# Generated by Django 2.2.4 on 2019-08-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0007_note_instrument'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='instrumentation_setting',
            field=models.CharField(default='blah', max_length=255),
            preserve_default=False,
        ),
    ]
