# Generated by Django 2.2.4 on 2019-08-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0010_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='identifying_code',
            field=models.CharField(default='asdfasd', max_length=255),
            preserve_default=False,
        ),
    ]
