# Generated by Django 2.2.4 on 2019-08-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0011_work_identifying_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='date_record_start_date',
        ),
        migrations.RemoveField(
            model_name='work',
            name='date_recorded_end_date',
        ),
    ]
