# Generated by Django 2.2.4 on 2019-08-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0012_auto_20190816_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_details',
            field=models.TextField(default='Not available'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='family',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='current_chord_root',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='current_chord_root_as_int',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='current_chord_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='harmony_note_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='quarter_beats_per_minute',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='time_signature_denominator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='time_signature_numerator',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_location',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='performance',
            name='performance_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='text',
            name='language',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='creation_location_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='creation_location_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='genre',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='identifying_code',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='instrumentation_setting',
            field=models.CharField(default='Not available', max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='notes',
            field=models.TextField(default='Not available'),
        ),
        migrations.AlterField(
            model_name='work',
            name='tonality',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
