# Generated by Django 2.2.4 on 2019-08-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0014_auto_20190816_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='title_in_original_language',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
