# Generated by Django 2.2.4 on 2019-08-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0015_work_title_in_original_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='instrumentation_setting',
            new_name='instrumentation_summary',
        ),
        migrations.AddField(
            model_name='work',
            name='type_of_work',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
