# Generated by Django 2.2.4 on 2019-09-04 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0018_auto_20190904_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='performance_notes',
            new_name='notes',
        ),
    ]
