# Generated by Django 2.2.4 on 2019-09-04 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0020_work_composed_date_approximate_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='composed_date_approximate_to',
            new_name='date_composed_approximate_to',
        ),
    ]
