# Generated by Django 2.2.4 on 2019-09-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0023_auto_20190905_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collection',
            old_name='collection_details',
            new_name='collection_notes',
        ),
        migrations.AddField(
            model_name='collection',
            name='title_in_original_language',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
