# Generated by Django 2.2.4 on 2019-09-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0025_auto_20190905_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='creation_location',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
