# Generated by Django 2.2.4 on 2019-09-06 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0027_auto_20190906_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performance',
            old_name='had_premiere_performance',
            new_name='is_premiere_performance',
        ),
    ]
