# Generated by Django 2.2.4 on 2019-09-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0028_auto_20190906_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='notes',
            field=models.TextField(default='Not available'),
        ),
    ]
