# Generated by Django 2.2.4 on 2019-09-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0029_performance_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='date_composed_end_date',
            new_name='composed_date_end',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='date_composed_approximate_to',
            new_name='composed_date_end_approximate_to',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='date_composed_start_date',
            new_name='composed_date_start',
        ),
        migrations.AddField(
            model_name='work',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='publication_date_approximate_to',
            field=models.CharField(default='Not available', max_length=255),
        ),
    ]
