# Generated by Django 2.2.5 on 2019-09-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0030_auto_20190907_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='score_available',
            field=models.BooleanField(default=False),
        ),
    ]
