# Generated by Django 2.2.5 on 2019-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0032_auto_20190923_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='duration_due_to_tied_notes',
            new_name='divisions',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='harmony_note_flag',
            new_name='is_grace_note',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='location_in_measure',
            new_name='starting_location',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='location_in_song_as_percentage',
            new_name='starting_location_of_measure',
        ),
        migrations.RemoveField(
            model_name='note',
            name='current_chord_root',
        ),
        migrations.RemoveField(
            model_name='note',
            name='current_chord_root_as_int',
        ),
        migrations.RemoveField(
            model_name='note',
            name='current_chord_type',
        ),
        migrations.RemoveField(
            model_name='note',
            name='time_stamp',
        ),
        migrations.RemoveField(
            model_name='note',
            name='voice',
        ),
        migrations.AddField(
            model_name='note',
            name='is_rest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='note_name',
            field=models.CharField(default='Not available', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='tie_status',
            field=models.CharField(default='Not applicable', max_length=50),
        ),
    ]
