# Generated by Django 2.2.5 on 2019-09-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0033_auto_20190924_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='has_instrumentation',
            field=models.BooleanField(default=True),
        ),
    ]
