# Generated by Django 2.2.5 on 2019-09-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0034_note_has_instrumentation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='location',
        ),
    ]
