# Generated by Django 2.2.5 on 2019-09-24 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0035_remove_note_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='starting_location_of_measure',
            new_name='starting_location_of_current_measure',
        ),
    ]
