# Generated by Django 2.2.5 on 2019-10-17 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0038_auto_20191014_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='composed_date_end_is_approximate',
            new_name='composed_end_date_is_approximate',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='composed_start_end_is_approximate',
            new_name='composed_start_date_is_approximate',
        ),
    ]
