# Generated by Django 2.2.5 on 2019-10-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0039_auto_20191017_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='performance_date_approximate_to',
        ),
        migrations.AddField(
            model_name='performance',
            name='performance_date_is_approximate',
            field=models.BooleanField(default=False),
        ),
    ]
