# Generated by Django 2.1.2 on 2018-10-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_and_notebooks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appornotebook',
            old_name='user',
            new_name='created_by',
        ),
    ]
