# Generated by Django 2.1.3 on 2018-11-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_and_notebooks', '0002_auto_20181017_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appornotebooktag',
            name='app_or_notebook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_or_notebook_tag', to='apps_and_notebooks.AppOrNotebook'),
        ),
    ]
