# Generated by Django 2.1.3 on 2018-11-09 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps_and_notebooks', '0003_auto_20181109_0724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('app_or_notebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='apps_and_notebooks.AppOrNotebook')),
            ],
        ),
        migrations.RemoveField(
            model_name='appornotebooktag',
            name='app_or_notebook',
        ),
        migrations.DeleteModel(
            name='AppOrNotebookTag',
        ),
    ]
