# Generated by Django 2.1.3 on 2018-11-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_and_notebooks', '0005_auto_20181109_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='appornotebook',
            name='type',
            field=models.CharField(default='App', max_length=50),
            preserve_default=False,
        ),
    ]
