# Generated by Django 2.1.3 on 2018-11-12 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_and_notebooks', '0006_appornotebook_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='app_or_notebook',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
