# Generated by Django 2.1.3 on 2018-11-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_and_notebooks', '0007_auto_20181112_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='RLibrary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
        ),
    ]
