# Generated by Django 2.1.3 on 2018-11-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_and_notebooks', '0008_rlibrary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appornotebook',
            name='location',
            field=models.CharField(max_length=255),
        ),
    ]
