# Generated by Django 2.2.5 on 2019-09-23 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_and_notebooks', '0009_auto_20181115_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RLibrary',
        ),
    ]
